# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ab3a019b351af0e47ec4c23de278b89d1f0a9137e63980f95e1f110e571742508e1527c3dd426508a1322dc15c4afbcfcb14d461fe9bf264bb5ee4220c221e4

test:
  secret_key_base: 3fb85d32cc95fcb2625b94b42cfd8b42ac4f05349af43e718a20ef444ed60d9d23f99889f4395623c35039b7e4cae34e64c06e0cd7a41163895b1b2efc66ec7d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
